name: Unit tests
on:
  push:
  pull_request:

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r process_report/tests/test-requirements.txt

      - name: Run unit tests
        run: |
          coverage run --source="." -m pytest process_report/tests/unit
          coverage combine
          coverage html --fail-under=80 --omit "process_report/tests/**"
